[package]
name = "lemurs"
authors = ["Gijs Burghoorn <me@gburghoorn.com>"]
description = "A TUI Display/Login Manager"
version = "0.2.0"

edition = "2021"

categories = ["gui", "authentication"]
keywords = ["display", "login", "desktop"]

repository = "https://github.com/coastalwhite/lemurs"
homepage = "https://github.com/coastalwhite/lemurs"

readme = "README.md"
license = "MIT or APACHE"

[dependencies]
tui = { version = "0.16.0", features = [ "crossterm" ] }
unicode-width = "0.1"
crossterm = { version = "0.22" }
pam = "0.7.0"
pgs-files = "0.0.7"
log = "0.4.0"
users = "0.11.0"
lazy_static = "1.4.0"
regex = "1.5"
fern = "0.5.2"
chvt = "0.2.0"
rand = "0.8.4"
chrono = "0.4"
nix = "0.23.1"
clap = { version = "3.0.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
hex = "0.4.3"
